/*
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.RpcStatus;
import org.openapitools.client.model.TitaniumDQErrorsRequest;
import org.openapitools.client.model.TitaniumDQErrorsResponse;
import org.openapitools.client.model.TitaniumGetDataQualityErrorsRequest;
import org.openapitools.client.model.TitaniumGetDataQualityErrorsResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DataQualityServiceApi
 */
@Disabled
public class DataQualityServiceApiTest {

    private final DataQualityServiceApi api = new DataQualityServiceApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dataQualityServiceDQErrorsTest() throws ApiException {
        TitaniumDQErrorsRequest body = null;
        TitaniumDQErrorsResponse response = api.dataQualityServiceDQErrors(body);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dataQualityServiceGetDataQualityErrorsTest() throws ApiException {
        TitaniumGetDataQualityErrorsRequest body = null;
        TitaniumGetDataQualityErrorsResponse response = api.dataQualityServiceGetDataQualityErrors(body);
        // TODO: test validations
    }

}
