# coding: utf-8

"""
    clearconsensus-sdk

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


try:
    from inspect import getfullargspec
except ImportError:
    from inspect import getargspec as getfullargspec
import pprint
import re  # noqa: F401
import six

from openapi_client.configuration import Configuration


class TitaniumAssetDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'asset_id': 'str',
        'date': 'str',
        'name': 'str',
        'service': 'str',
        'snap_time': 'str',
        'sub_asset': 'str'
    }

    attribute_map = {
        'asset_id': 'assetId',
        'date': 'date',
        'name': 'name',
        'service': 'service',
        'snap_time': 'snapTime',
        'sub_asset': 'subAsset'
    }

    def __init__(self, asset_id=None, date=None, name=None, service=None, snap_time=None, sub_asset=None, local_vars_configuration=None):  # noqa: E501
        """TitaniumAssetDetails - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration.get_default_copy()
        self.local_vars_configuration = local_vars_configuration

        self._asset_id = None
        self._date = None
        self._name = None
        self._service = None
        self._snap_time = None
        self._sub_asset = None
        self.discriminator = None

        if asset_id is not None:
            self.asset_id = asset_id
        if date is not None:
            self.date = date
        if name is not None:
            self.name = name
        if service is not None:
            self.service = service
        if snap_time is not None:
            self.snap_time = snap_time
        if sub_asset is not None:
            self.sub_asset = sub_asset

    @property
    def asset_id(self):
        """Gets the asset_id of this TitaniumAssetDetails.  # noqa: E501


        :return: The asset_id of this TitaniumAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._asset_id

    @asset_id.setter
    def asset_id(self, asset_id):
        """Sets the asset_id of this TitaniumAssetDetails.


        :param asset_id: The asset_id of this TitaniumAssetDetails.  # noqa: E501
        :type asset_id: str
        """

        self._asset_id = asset_id

    @property
    def date(self):
        """Gets the date of this TitaniumAssetDetails.  # noqa: E501


        :return: The date of this TitaniumAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._date

    @date.setter
    def date(self, date):
        """Sets the date of this TitaniumAssetDetails.


        :param date: The date of this TitaniumAssetDetails.  # noqa: E501
        :type date: str
        """

        self._date = date

    @property
    def name(self):
        """Gets the name of this TitaniumAssetDetails.  # noqa: E501


        :return: The name of this TitaniumAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TitaniumAssetDetails.


        :param name: The name of this TitaniumAssetDetails.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def service(self):
        """Gets the service of this TitaniumAssetDetails.  # noqa: E501


        :return: The service of this TitaniumAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service):
        """Sets the service of this TitaniumAssetDetails.


        :param service: The service of this TitaniumAssetDetails.  # noqa: E501
        :type service: str
        """

        self._service = service

    @property
    def snap_time(self):
        """Gets the snap_time of this TitaniumAssetDetails.  # noqa: E501


        :return: The snap_time of this TitaniumAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._snap_time

    @snap_time.setter
    def snap_time(self, snap_time):
        """Sets the snap_time of this TitaniumAssetDetails.


        :param snap_time: The snap_time of this TitaniumAssetDetails.  # noqa: E501
        :type snap_time: str
        """

        self._snap_time = snap_time

    @property
    def sub_asset(self):
        """Gets the sub_asset of this TitaniumAssetDetails.  # noqa: E501


        :return: The sub_asset of this TitaniumAssetDetails.  # noqa: E501
        :rtype: str
        """
        return self._sub_asset

    @sub_asset.setter
    def sub_asset(self, sub_asset):
        """Sets the sub_asset of this TitaniumAssetDetails.


        :param sub_asset: The sub_asset of this TitaniumAssetDetails.  # noqa: E501
        :type sub_asset: str
        """

        self._sub_asset = sub_asset

    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TitaniumAssetDetails):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TitaniumAssetDetails):
            return True

        return self.to_dict() != other.to_dict()
