/*
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TitaniumTradeAnchorDetails
 */
public class TitaniumTradeAnchorDetailsTest {
    private final TitaniumTradeAnchorDetails model = new TitaniumTradeAnchorDetails();

    /**
     * Model tests for TitaniumTradeAnchorDetails
     */
    @Test
    public void testTitaniumTradeAnchorDetails() {
        // TODO: test TitaniumTradeAnchorDetails
    }

    /**
     * Test the property 'distanceToConsensus'
     */
    @Test
    public void distanceToConsensusTest() {
        // TODO: test distanceToConsensus
    }

    /**
     * Test the property 'latestTradePrice'
     */
    @Test
    public void latestTradePriceTest() {
        // TODO: test latestTradePrice
    }

    /**
     * Test the property 'notional'
     */
    @Test
    public void notionalTest() {
        // TODO: test notional
    }

    /**
     * Test the property 'pricingAge'
     */
    @Test
    public void pricingAgeTest() {
        // TODO: test pricingAge
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'tradeExecutionTime'
     */
    @Test
    public void tradeExecutionTimeTest() {
        // TODO: test tradeExecutionTime
    }

}
