/*
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TitaniumPredefinedFilter
 */
public class TitaniumPredefinedFilterTest {
    private final TitaniumPredefinedFilter model = new TitaniumPredefinedFilter();

    /**
     * Model tests for TitaniumPredefinedFilter
     */
    @Test
    public void testTitaniumPredefinedFilter() {
        // TODO: test TitaniumPredefinedFilter
    }

    /**
     * Test the property 'key'
     */
    @Test
    public void keyTest() {
        // TODO: test key
    }

    /**
     * Test the property 'operator'
     */
    @Test
    public void operatorTest() {
        // TODO: test operator
    }

    /**
     * Test the property 'predefinedValueLabel'
     */
    @Test
    public void predefinedValueLabelTest() {
        // TODO: test predefinedValueLabel
    }

    /**
     * Test the property 'resultCount'
     */
    @Test
    public void resultCountTest() {
        // TODO: test resultCount
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
