/*
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.TitaniumCriteriaDefinition;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TitaniumRulesetDefinition
 */
public class TitaniumRulesetDefinitionTest {
    private final TitaniumRulesetDefinition model = new TitaniumRulesetDefinition();

    /**
     * Model tests for TitaniumRulesetDefinition
     */
    @Test
    public void testTitaniumRulesetDefinition() {
        // TODO: test TitaniumRulesetDefinition
    }

    /**
     * Test the property 'criteria'
     */
    @Test
    public void criteriaTest() {
        // TODO: test criteria
    }

    /**
     * Test the property 'descriptorName'
     */
    @Test
    public void descriptorNameTest() {
        // TODO: test descriptorName
    }

}
