/*
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.TitaniumRulesetDefinition;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TitaniumValidationRuleDefinition
 */
public class TitaniumValidationRuleDefinitionTest {
    private final TitaniumValidationRuleDefinition model = new TitaniumValidationRuleDefinition();

    /**
     * Model tests for TitaniumValidationRuleDefinition
     */
    @Test
    public void testTitaniumValidationRuleDefinition() {
        // TODO: test TitaniumValidationRuleDefinition
    }

    /**
     * Test the property 'definition'
     */
    @Test
    public void definitionTest() {
        // TODO: test definition
    }

    /**
     * Test the property 'descriptorName'
     */
    @Test
    public void descriptorNameTest() {
        // TODO: test descriptorName
    }

    /**
     * Test the property 'scope'
     */
    @Test
    public void scopeTest() {
        // TODO: test scope
    }

    /**
     * Test the property 'uid'
     */
    @Test
    public void uidTest() {
        // TODO: test uid
    }

}
