/*
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TitaniumDQError
 */
public class TitaniumDQErrorTest {
    private final TitaniumDQError model = new TitaniumDQError();

    /**
     * Model tests for TitaniumDQError
     */
    @Test
    public void testTitaniumDQError() {
        // TODO: test TitaniumDQError
    }

    /**
     * Test the property 'criteriaName'
     */
    @Test
    public void criteriaNameTest() {
        // TODO: test criteriaName
    }

    /**
     * Test the property 'errorMessage'
     */
    @Test
    public void errorMessageTest() {
        // TODO: test errorMessage
    }

    /**
     * Test the property 'ruleName'
     */
    @Test
    public void ruleNameTest() {
        // TODO: test ruleName
    }

    /**
     * Test the property 'rulesetName'
     */
    @Test
    public void rulesetNameTest() {
        // TODO: test rulesetName
    }

    /**
     * Test the property 'severity'
     */
    @Test
    public void severityTest() {
        // TODO: test severity
    }

}
