"""
    clearconsensus-sdk

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.titanium_limit import TitaniumLimit
globals()['TitaniumLimit'] = TitaniumLimit
from openapi_client.model.titanium_get_supported_fields import TitaniumGetSupportedFields


class TestTitaniumGetSupportedFields(unittest.TestCase):
    """TitaniumGetSupportedFields unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTitaniumGetSupportedFields(self):
        """Test TitaniumGetSupportedFields"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TitaniumGetSupportedFields()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
