"""
    clearconsensus-sdk

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.titanium_column_info import TitaniumColumnInfo
from openapi_client.model.titanium_values_row import TitaniumValuesRow
globals()['TitaniumColumnInfo'] = TitaniumColumnInfo
globals()['TitaniumValuesRow'] = TitaniumValuesRow
from openapi_client.model.titanium_challenge_history_response_data import TitaniumChallengeHistoryResponseData


class TestTitaniumChallengeHistoryResponseData(unittest.TestCase):
    """TitaniumChallengeHistoryResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTitaniumChallengeHistoryResponseData(self):
        """Test TitaniumChallengeHistoryResponseData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TitaniumChallengeHistoryResponseData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
