"""
    clearconsensus-sdk

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.titanium_evp_anchor_details import TitaniumEvpAnchorDetails


class TestTitaniumEvpAnchorDetails(unittest.TestCase):
    """TitaniumEvpAnchorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTitaniumEvpAnchorDetails(self):
        """Test TitaniumEvpAnchorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TitaniumEvpAnchorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
