# coding: utf-8

"""
    clearconsensus-sdk

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.admin_service_api import AdminServiceApi  # noqa: E501
from openapi_client.rest import ApiException


class TestAdminServiceApi(unittest.TestCase):
    """AdminServiceApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.admin_service_api.AdminServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_service_on_board(self):
        """Test case for admin_service_on_board

        """
        pass

    def test_admin_service_run_calculator(self):
        """Test case for admin_service_run_calculator

        """
        pass

    def test_admin_service_run_consensus(self):
        """Test case for admin_service_run_consensus

        """
        pass

    def test_admin_service_upload_evaluated_price(self):
        """Test case for admin_service_upload_evaluated_price

        """
        pass


if __name__ == '__main__':
    unittest.main()
