/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ErrorValidationErrorDetail model module.
 * @module model/ErrorValidationErrorDetail
 * @version 1.0.0
 */
class ErrorValidationErrorDetail {
    /**
     * Constructs a new <code>ErrorValidationErrorDetail</code>.
     * @alias module:model/ErrorValidationErrorDetail
     */
    constructor() { 
        
        ErrorValidationErrorDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ErrorValidationErrorDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ErrorValidationErrorDetail} obj Optional instance to populate.
     * @return {module:model/ErrorValidationErrorDetail} The populated <code>ErrorValidationErrorDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorValidationErrorDetail();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('fieldName')) {
                obj['fieldName'] = ApiClient.convertToType(data['fieldName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} description
 */
ErrorValidationErrorDetail.prototype['description'] = undefined;

/**
 * @member {String} fieldName
 */
ErrorValidationErrorDetail.prototype['fieldName'] = undefined;






export default ErrorValidationErrorDetail;

