/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetFileExportUrlResponseFileExportUrl from './GetFileExportUrlResponseFileExportUrl';
import TitaniumError from './TitaniumError';

/**
 * The TitaniumGetFileExportUrlResponse model module.
 * @module model/TitaniumGetFileExportUrlResponse
 * @version 1.0.0
 */
class TitaniumGetFileExportUrlResponse {
    /**
     * Constructs a new <code>TitaniumGetFileExportUrlResponse</code>.
     * @alias module:model/TitaniumGetFileExportUrlResponse
     */
    constructor() { 
        
        TitaniumGetFileExportUrlResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumGetFileExportUrlResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumGetFileExportUrlResponse} obj Optional instance to populate.
     * @return {module:model/TitaniumGetFileExportUrlResponse} The populated <code>TitaniumGetFileExportUrlResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumGetFileExportUrlResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = GetFileExportUrlResponseFileExportUrl.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = TitaniumError.constructFromObject(data['error']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GetFileExportUrlResponseFileExportUrl} data
 */
TitaniumGetFileExportUrlResponse.prototype['data'] = undefined;

/**
 * @member {module:model/TitaniumError} error
 */
TitaniumGetFileExportUrlResponse.prototype['error'] = undefined;






export default TitaniumGetFileExportUrlResponse;

