/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TitaniumUserNotification from './TitaniumUserNotification';

/**
 * The TitaniumUserNotificationRequest model module.
 * @module model/TitaniumUserNotificationRequest
 * @version 1.0.0
 */
class TitaniumUserNotificationRequest {
    /**
     * Constructs a new <code>TitaniumUserNotificationRequest</code>.
     * @alias module:model/TitaniumUserNotificationRequest
     */
    constructor() { 
        
        TitaniumUserNotificationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumUserNotificationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumUserNotificationRequest} obj Optional instance to populate.
     * @return {module:model/TitaniumUserNotificationRequest} The populated <code>TitaniumUserNotificationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumUserNotificationRequest();

            if (data.hasOwnProperty('userNotification')) {
                obj['userNotification'] = TitaniumUserNotification.constructFromObject(data['userNotification']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TitaniumUserNotification} userNotification
 */
TitaniumUserNotificationRequest.prototype['userNotification'] = undefined;






export default TitaniumUserNotificationRequest;

