/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TitaniumReprocessWorkflowRequest model module.
 * @module model/TitaniumReprocessWorkflowRequest
 * @version 1.0.0
 */
class TitaniumReprocessWorkflowRequest {
    /**
     * Constructs a new <code>TitaniumReprocessWorkflowRequest</code>.
     * @alias module:model/TitaniumReprocessWorkflowRequest
     */
    constructor() { 
        
        TitaniumReprocessWorkflowRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumReprocessWorkflowRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumReprocessWorkflowRequest} obj Optional instance to populate.
     * @return {module:model/TitaniumReprocessWorkflowRequest} The populated <code>TitaniumReprocessWorkflowRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumReprocessWorkflowRequest();

            if (data.hasOwnProperty('runId')) {
                obj['runId'] = ApiClient.convertToType(data['runId'], 'String');
            }
            if (data.hasOwnProperty('workflowId')) {
                obj['workflowId'] = ApiClient.convertToType(data['workflowId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} runId
 */
TitaniumReprocessWorkflowRequest.prototype['runId'] = undefined;

/**
 * @member {String} workflowId
 */
TitaniumReprocessWorkflowRequest.prototype['workflowId'] = undefined;






export default TitaniumReprocessWorkflowRequest;

