/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TitaniumRange from './TitaniumRange';

/**
 * The TitaniumChartRanges model module.
 * @module model/TitaniumChartRanges
 * @version 1.0.0
 */
class TitaniumChartRanges {
    /**
     * Constructs a new <code>TitaniumChartRanges</code>.
     * @alias module:model/TitaniumChartRanges
     */
    constructor() { 
        
        TitaniumChartRanges.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumChartRanges</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumChartRanges} obj Optional instance to populate.
     * @return {module:model/TitaniumChartRanges} The populated <code>TitaniumChartRanges</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumChartRanges();

            if (data.hasOwnProperty('bimodalLeftPopulation')) {
                obj['bimodalLeftPopulation'] = TitaniumRange.constructFromObject(data['bimodalLeftPopulation']);
            }
            if (data.hasOwnProperty('bimodalRightPopulation')) {
                obj['bimodalRightPopulation'] = TitaniumRange.constructFromObject(data['bimodalRightPopulation']);
            }
            if (data.hasOwnProperty('challengeOverlayConsensus')) {
                obj['challengeOverlayConsensus'] = TitaniumRange.constructFromObject(data['challengeOverlayConsensus']);
            }
            if (data.hasOwnProperty('evp')) {
                obj['evp'] = TitaniumRange.constructFromObject(data['evp']);
            }
            if (data.hasOwnProperty('expertPostChallenge')) {
                obj['expertPostChallenge'] = TitaniumRange.constructFromObject(data['expertPostChallenge']);
            }
            if (data.hasOwnProperty('expertPreChallenge')) {
                obj['expertPreChallenge'] = TitaniumRange.constructFromObject(data['expertPreChallenge']);
            }
            if (data.hasOwnProperty('marketDataOverlayConsensus')) {
                obj['marketDataOverlayConsensus'] = TitaniumRange.constructFromObject(data['marketDataOverlayConsensus']);
            }
            if (data.hasOwnProperty('submissionMeanMedian')) {
                obj['submissionMeanMedian'] = TitaniumRange.constructFromObject(data['submissionMeanMedian']);
            }
            if (data.hasOwnProperty('submissionMinMax')) {
                obj['submissionMinMax'] = TitaniumRange.constructFromObject(data['submissionMinMax']);
            }
            if (data.hasOwnProperty('submissionOnlyConsensus')) {
                obj['submissionOnlyConsensus'] = TitaniumRange.constructFromObject(data['submissionOnlyConsensus']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TitaniumRange} bimodalLeftPopulation
 */
TitaniumChartRanges.prototype['bimodalLeftPopulation'] = undefined;

/**
 * @member {module:model/TitaniumRange} bimodalRightPopulation
 */
TitaniumChartRanges.prototype['bimodalRightPopulation'] = undefined;

/**
 * @member {module:model/TitaniumRange} challengeOverlayConsensus
 */
TitaniumChartRanges.prototype['challengeOverlayConsensus'] = undefined;

/**
 * @member {module:model/TitaniumRange} evp
 */
TitaniumChartRanges.prototype['evp'] = undefined;

/**
 * @member {module:model/TitaniumRange} expertPostChallenge
 */
TitaniumChartRanges.prototype['expertPostChallenge'] = undefined;

/**
 * @member {module:model/TitaniumRange} expertPreChallenge
 */
TitaniumChartRanges.prototype['expertPreChallenge'] = undefined;

/**
 * @member {module:model/TitaniumRange} marketDataOverlayConsensus
 */
TitaniumChartRanges.prototype['marketDataOverlayConsensus'] = undefined;

/**
 * @member {module:model/TitaniumRange} submissionMeanMedian
 */
TitaniumChartRanges.prototype['submissionMeanMedian'] = undefined;

/**
 * @member {module:model/TitaniumRange} submissionMinMax
 */
TitaniumChartRanges.prototype['submissionMinMax'] = undefined;

/**
 * @member {module:model/TitaniumRange} submissionOnlyConsensus
 */
TitaniumChartRanges.prototype['submissionOnlyConsensus'] = undefined;






export default TitaniumChartRanges;

