/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TitaniumPredefinedFilter model module.
 * @module model/TitaniumPredefinedFilter
 * @version 1.0.0
 */
class TitaniumPredefinedFilter {
    /**
     * Constructs a new <code>TitaniumPredefinedFilter</code>.
     * @alias module:model/TitaniumPredefinedFilter
     */
    constructor() { 
        
        TitaniumPredefinedFilter.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumPredefinedFilter</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumPredefinedFilter} obj Optional instance to populate.
     * @return {module:model/TitaniumPredefinedFilter} The populated <code>TitaniumPredefinedFilter</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumPredefinedFilter();

            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
            if (data.hasOwnProperty('predefinedValueLabel')) {
                obj['predefinedValueLabel'] = ApiClient.convertToType(data['predefinedValueLabel'], 'String');
            }
            if (data.hasOwnProperty('resultCount')) {
                obj['resultCount'] = ApiClient.convertToType(data['resultCount'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} key
 */
TitaniumPredefinedFilter.prototype['key'] = undefined;

/**
 * @member {String} operator
 */
TitaniumPredefinedFilter.prototype['operator'] = undefined;

/**
 * @member {String} predefinedValueLabel
 */
TitaniumPredefinedFilter.prototype['predefinedValueLabel'] = undefined;

/**
 * @member {Number} resultCount
 */
TitaniumPredefinedFilter.prototype['resultCount'] = undefined;

/**
 * @member {Object} value
 */
TitaniumPredefinedFilter.prototype['value'] = undefined;






export default TitaniumPredefinedFilter;

