/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TitaniumChallengeFormGeneralRowMax from './TitaniumChallengeFormGeneralRowMax';
import TitaniumChallengeFormGeneralRowMaxLength from './TitaniumChallengeFormGeneralRowMaxLength';
import TitaniumChallengeFormGeneralRowMin from './TitaniumChallengeFormGeneralRowMin';
import TitaniumChallengeFormGeneralRowMinLength from './TitaniumChallengeFormGeneralRowMinLength';
import TitaniumChallengeFormGeneralRowPrecision from './TitaniumChallengeFormGeneralRowPrecision';

/**
 * The TitaniumChallengeFormGeneralRow model module.
 * @module model/TitaniumChallengeFormGeneralRow
 * @version 1.0.0
 */
class TitaniumChallengeFormGeneralRow {
    /**
     * Constructs a new <code>TitaniumChallengeFormGeneralRow</code>.
     * @alias module:model/TitaniumChallengeFormGeneralRow
     */
    constructor() { 
        
        TitaniumChallengeFormGeneralRow.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumChallengeFormGeneralRow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumChallengeFormGeneralRow} obj Optional instance to populate.
     * @return {module:model/TitaniumChallengeFormGeneralRow} The populated <code>TitaniumChallengeFormGeneralRow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumChallengeFormGeneralRow();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('max')) {
                obj['max'] = TitaniumChallengeFormGeneralRowMax.constructFromObject(data['max']);
            }
            if (data.hasOwnProperty('maxLength')) {
                obj['maxLength'] = TitaniumChallengeFormGeneralRowMaxLength.constructFromObject(data['maxLength']);
            }
            if (data.hasOwnProperty('min')) {
                obj['min'] = TitaniumChallengeFormGeneralRowMin.constructFromObject(data['min']);
            }
            if (data.hasOwnProperty('minLength')) {
                obj['minLength'] = TitaniumChallengeFormGeneralRowMinLength.constructFromObject(data['minLength']);
            }
            if (data.hasOwnProperty('precision')) {
                obj['precision'] = TitaniumChallengeFormGeneralRowPrecision.constructFromObject(data['precision']);
            }
            if (data.hasOwnProperty('regex')) {
                obj['regex'] = ApiClient.convertToType(data['regex'], 'String');
            }
            if (data.hasOwnProperty('tooltip')) {
                obj['tooltip'] = ApiClient.convertToType(data['tooltip'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} field
 */
TitaniumChallengeFormGeneralRow.prototype['field'] = undefined;

/**
 * @member {module:model/TitaniumChallengeFormGeneralRowMax} max
 */
TitaniumChallengeFormGeneralRow.prototype['max'] = undefined;

/**
 * @member {module:model/TitaniumChallengeFormGeneralRowMaxLength} maxLength
 */
TitaniumChallengeFormGeneralRow.prototype['maxLength'] = undefined;

/**
 * @member {module:model/TitaniumChallengeFormGeneralRowMin} min
 */
TitaniumChallengeFormGeneralRow.prototype['min'] = undefined;

/**
 * @member {module:model/TitaniumChallengeFormGeneralRowMinLength} minLength
 */
TitaniumChallengeFormGeneralRow.prototype['minLength'] = undefined;

/**
 * @member {module:model/TitaniumChallengeFormGeneralRowPrecision} precision
 */
TitaniumChallengeFormGeneralRow.prototype['precision'] = undefined;

/**
 * @member {String} regex
 */
TitaniumChallengeFormGeneralRow.prototype['regex'] = undefined;

/**
 * @member {String} tooltip
 */
TitaniumChallengeFormGeneralRow.prototype['tooltip'] = undefined;

/**
 * @member {String} type
 */
TitaniumChallengeFormGeneralRow.prototype['type'] = undefined;

/**
 * @member {Object} value
 */
TitaniumChallengeFormGeneralRow.prototype['value'] = undefined;






export default TitaniumChallengeFormGeneralRow;

