/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TitaniumDQError from './TitaniumDQError';

/**
 * The TitaniumSeverityToDataQuality model module.
 * @module model/TitaniumSeverityToDataQuality
 * @version 1.0.0
 */
class TitaniumSeverityToDataQuality {
    /**
     * Constructs a new <code>TitaniumSeverityToDataQuality</code>.
     * @alias module:model/TitaniumSeverityToDataQuality
     */
    constructor() { 
        
        TitaniumSeverityToDataQuality.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumSeverityToDataQuality</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumSeverityToDataQuality} obj Optional instance to populate.
     * @return {module:model/TitaniumSeverityToDataQuality} The populated <code>TitaniumSeverityToDataQuality</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumSeverityToDataQuality();

            if (data.hasOwnProperty('high')) {
                obj['high'] = ApiClient.convertToType(data['high'], [TitaniumDQError]);
            }
            if (data.hasOwnProperty('low')) {
                obj['low'] = ApiClient.convertToType(data['low'], [TitaniumDQError]);
            }
            if (data.hasOwnProperty('medium')) {
                obj['medium'] = ApiClient.convertToType(data['medium'], [TitaniumDQError]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TitaniumDQError>} high
 */
TitaniumSeverityToDataQuality.prototype['high'] = undefined;

/**
 * @member {Array.<module:model/TitaniumDQError>} low
 */
TitaniumSeverityToDataQuality.prototype['low'] = undefined;

/**
 * @member {Array.<module:model/TitaniumDQError>} medium
 */
TitaniumSeverityToDataQuality.prototype['medium'] = undefined;






export default TitaniumSeverityToDataQuality;

