/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TitaniumAsset from './TitaniumAsset';

/**
 * The TitaniumAssetsList model module.
 * @module model/TitaniumAssetsList
 * @version 1.0.0
 */
class TitaniumAssetsList {
    /**
     * Constructs a new <code>TitaniumAssetsList</code>.
     * @alias module:model/TitaniumAssetsList
     */
    constructor() { 
        
        TitaniumAssetsList.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumAssetsList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumAssetsList} obj Optional instance to populate.
     * @return {module:model/TitaniumAssetsList} The populated <code>TitaniumAssetsList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumAssetsList();

            if (data.hasOwnProperty('assets')) {
                obj['assets'] = ApiClient.convertToType(data['assets'], [TitaniumAsset]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/TitaniumAsset>} assets
 */
TitaniumAssetsList.prototype['assets'] = undefined;






export default TitaniumAssetsList;

