/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TitaniumError from './TitaniumError';
import TitaniumUser from './TitaniumUser';

/**
 * The TitaniumUserResponse model module.
 * @module model/TitaniumUserResponse
 * @version 1.0.0
 */
class TitaniumUserResponse {
    /**
     * Constructs a new <code>TitaniumUserResponse</code>.
     * @alias module:model/TitaniumUserResponse
     */
    constructor() { 
        
        TitaniumUserResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TitaniumUserResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TitaniumUserResponse} obj Optional instance to populate.
     * @return {module:model/TitaniumUserResponse} The populated <code>TitaniumUserResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TitaniumUserResponse();

            if (data.hasOwnProperty('error')) {
                obj['error'] = TitaniumError.constructFromObject(data['error']);
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = TitaniumUser.constructFromObject(data['user']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/TitaniumError} error
 */
TitaniumUserResponse.prototype['error'] = undefined;

/**
 * @member {module:model/TitaniumUser} user
 */
TitaniumUserResponse.prototype['user'] = undefined;






export default TitaniumUserResponse;

