/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClearconsensusSdk);
  }
}(this, function(expect, ClearconsensusSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ClearconsensusSdk.TitaniumActionDefinition();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TitaniumActionDefinition', function() {
    it('should create an instance of TitaniumActionDefinition', function() {
      // uncomment below and update the code to test TitaniumActionDefinition
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be.a(ClearconsensusSdk.TitaniumActionDefinition);
    });

    it('should have the property actionType (base name: "actionType")', function() {
      // uncomment below and update the code to test the property actionType
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property dependsOn (base name: "dependsOn")', function() {
      // uncomment below and update the code to test the property dependsOn
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property doNotRunIf (base name: "doNotRunIf")', function() {
      // uncomment below and update the code to test the property doNotRunIf
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property ignoreFailure (base name: "ignoreFailure")', function() {
      // uncomment below and update the code to test the property ignoreFailure
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property inputArguments (base name: "inputArguments")', function() {
      // uncomment below and update the code to test the property inputArguments
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property outputArgument (base name: "outputArgument")', function() {
      // uncomment below and update the code to test the property outputArgument
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property queue (base name: "queue")', function() {
      // uncomment below and update the code to test the property queue
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property retries (base name: "retries")', function() {
      // uncomment below and update the code to test the property retries
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property runIf (base name: "runIf")', function() {
      // uncomment below and update the code to test the property runIf
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

    it('should have the property timeoutSeconds (base name: "timeoutSeconds")', function() {
      // uncomment below and update the code to test the property timeoutSeconds
      //var instance = new ClearconsensusSdk.TitaniumActionDefinition();
      //expect(instance).to.be();
    });

  });

}));
