/**
 * clearconsensus-sdk
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ClearconsensusSdk);
  }
}(this, function(expect, ClearconsensusSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ClearconsensusSdk.TitaniumChartRanges();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TitaniumChartRanges', function() {
    it('should create an instance of TitaniumChartRanges', function() {
      // uncomment below and update the code to test TitaniumChartRanges
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be.a(ClearconsensusSdk.TitaniumChartRanges);
    });

    it('should have the property challengeOverlayConsensus (base name: "challengeOverlayConsensus")', function() {
      // uncomment below and update the code to test the property challengeOverlayConsensus
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property evp (base name: "evp")', function() {
      // uncomment below and update the code to test the property evp
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property expertPostChallenge (base name: "expertPostChallenge")', function() {
      // uncomment below and update the code to test the property expertPostChallenge
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property expertPreChallenge (base name: "expertPreChallenge")', function() {
      // uncomment below and update the code to test the property expertPreChallenge
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property marketDataOverlayConsensus (base name: "marketDataOverlayConsensus")', function() {
      // uncomment below and update the code to test the property marketDataOverlayConsensus
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property submissionMeanMedian (base name: "submissionMeanMedian")', function() {
      // uncomment below and update the code to test the property submissionMeanMedian
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property submissionMinMax (base name: "submissionMinMax")', function() {
      // uncomment below and update the code to test the property submissionMinMax
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

    it('should have the property submissionOnlyConsensus (base name: "submissionOnlyConsensus")', function() {
      // uncomment below and update the code to test the property submissionOnlyConsensus
      //var instance = new ClearconsensusSdk.TitaniumChartRanges();
      //expect(instance).to.be();
    });

  });

}));
